### ISSUE TITLE
brken link for full book download

### ISSUE THREAD

**Issue by prochlorothrix** [albertoacerbi/IBM-cultevo#1]
I'd love to read your book on my ebook reader (much easier than on a webpage) but the link on the https://acerbialberto.com/IBM-cultevo/ seems broken (both for epub and pdf) and I was unable to find the built files here. I would be grateful if you could fix that. A good epub version would be especially appreciated

**Comment by albertoacerbi** [comment]
Thank you for your interest! As we thought the book to be used with the code, there is not currently an epub version. If it can be useful, there is a pdf version here: [https://osf.io/32v6a](https://osf.io/32v6a)
I hope this helps!
